apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops
  labels:
    app: mlops
spec:
  selector:
    matchLabels:
        app: mlops
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - name: mlops
          image: 649225658490.dkr.ecr.ap-south-1.amazonaws.com/mlops:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
